config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      post "encode", to: "short_urls#encode"
      post "decode", to: "short_urls#decode"
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "short_urls#new"
  resources :short_urls, only: [ :index, :show, :new, :create ]
  get "/:code", to: "short_urls#redirect", as: :short
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/short_url.rb
class ShortUrl < ApplicationRecord
  require "net/http"
  require "uri"
  # TODO: length as 7 is enough i think maybe change it later
  CODE_LENGTH = 7
  before_validation :generate_code, on: :create
  before_validation :fix_url, on: :create

  validates :original_url, presence: true
  validates :code, presence: true, uniqueness: true, length: { is: CODE_LENGTH }, if: -> { original_url.present? }
  validate :check_url, if: -> { original_url.present? }

  # check if url starts with http or https add if missing and parse the url to make sure the formate is valid
  def fix_url
    return if original_url.blank?

    unless original_url.match?(/\Ahttp(s)?:\/\//)
      self.original_url = "https://#{original_url}"
    end

    parsed = URI.parse(original_url)

    unless parsed.is_a?(URI::HTTP) && parsed.host.present?
      errors.add(:original_url, "not a valid http or https link")
      return
    end

    self.original_url = parsed.to_s
  rescue URI::InvalidURIError
      errors.add(:original_url, "not a valid http or https link")
  end

  # make a request to the url and check if its a real used url
  def check_url
    return if original_url.blank?

    parsed = URI.parse(original_url)

    http = Net::HTTP.new(parsed.host, parsed.port)
    http.use_ssl = (parsed.scheme == "https")
    http.open_timeout = 3
    http.read_timeout = 6

    response = http.request_head(parsed.request_uri)

    unless response.is_a?(Net::HTTPSuccess) || response.is_a?(Net::HTTPRedirection)
      errors.add(:original_url, "no site with this url #{response.code}")
    end
  rescue StandardError => e
    errors.add(:original_url, "no site with this url #{e.message}")
  end

  def generate_code
    return if original_url.blank? || code.present?
    # while loop that breaks when the generated code is not a duplicate
    loop do
      self.code = SecureRandom.alphanumeric(CODE_LENGTH)
      break unless ShortUrl.exists?(code: code)
    end
  end
end

app/controllers/api/v1/short_urls_controller.rb
class Api::V1::ShortUrlsController < ApplicationController
  protect_from_forgery with: :null_session
  rate_limit to: 10, within: 3.minutes, only: :encode, with: -> { render_too_many_requests }

  def encode
    short_url = ShortUrl.new(encode_params)

    if short_url.save
      render json: {
        success: true,
        data: {
          original_url: short_url.original_url,
          code: short_url.code
        }
      }, status: :created
    else
      render json: {
        success: false,
        errors: short_url.errors.full_messages
      }, status: :unprocessable_entity
    end
  end

  def decode
    short_url = ShortUrl.find_by(code: decode_params[:code])
    if short_url
    render json: {
        success: true,
        data: {
          original_url: short_url.original_url,
          code: short_url.code
        }
      }
    else
      render json: {
        success: false,
        error: "Short URL not found"
      }, status: :not_found
    end
  end

  private
  def decode_params
    params.permit(:code)
  end
  def encode_params
    params.permit(:original_url)
  end

  def render_too_many_requests
    render json: {
      success: false,
      error: "Too many requests. Please try again later."
    }, status: :too_many_requests
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes
end

app/controllers/short_urls_controller.rb
class ShortUrlsController < ApplicationController
  before_action :set_short_url, only: [ :show ]
  def index
    @short_urls = ShortUrl.all
  end

  def new
    @short_url = ShortUrl.new
  end

  def show
  end

  def create
    @short_url = ShortUrl.new(short_url_params)

    if @short_url.save
      redirect_to @short_url, notice: "created successfully"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def redirect
    @short_url = ShortUrl.find_by(code: params[:code])
    if @short_url
      redirect_to @short_url.original_url, allow_other_host: true
    else
      # TODO: change this to not found page
      render plain: "URL not found", status: :not_found
    end
  end

  private

  def set_short_url
    @short_url = ShortUrl.find(params[:id])
  end

  def short_url_params
    params.require(:short_url).permit(:original_url)
  end
end

app/helpers/api/v1/short_urls_helper.rb
module Api::V1::ShortUrlsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/short_urls_helper.rb
module ShortUrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Url Task" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Url Task">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/short_urls/index.html.erb
<h1>ShortUrl#index</h1>

<ul>
    <% @short_urls.each do |short_url| %>
        <li>
            <%= link_to short_url  do %>
                <%= short_url.original_url %> <span style="margin: 0 10px"><%= short_url.code %></span>
            <%end%>
        </li>
    <% end%> 
</ul>

app/views/short_urls/new.html.erb
<div class="center-container full-height">
  <div id="short-urls-new" class="center-main">
    <h2>Create Your Short Url</h2>
    <div class="form-container">
    <%= form_with model: @short_url, local: true do |form| %>
      <% if @short_url.errors.any? %>
        <div class="errors">
          <ul>
            <% @short_url.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form">
        <%= form.text_field :original_url, placeholder: "Put your url here" %>
        <div class="center-container btn-container">
          <%= form.submit "Create Short URL", class: "btn" %>
        </div>
        
      </div>
    <% end %>
    </div>
</div>

app/views/short_urls/show.html.erb
<div class="center-container full-height">
  <div class="center-main">
    <h2>This is your URL</h2>
    <div>
      <div class="short-container"><%= @short_url.code %></div>
        <div style="text-align:center">
          <div>try your url <%= link_to "here", short_path(@short_url.code) %><div>
          <%= link_to "Create new URL", root_path, class: "btn"%>
        <div>
    </div>
  </div>
</div>